bazel_dep(name = "rules_cc", version = "0.0.9")
new_local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

new_local_repository(
    name = "macos_opencv",
    build_file = "//third_party:macos_opencv.BUILD",
    path = "/opt/homebrew/opt/opencv",
)

new_local_repository(
    name = "macos_mlx",
    build_file = "//third_party:mlx.BUILD",
    path = "/usr/local",
)
